// Generated by scripts/sync_reflex.py from solari-reflex dist/page/observer.js. Do not edit.
// OBSERVER_VERSION = 3
function installObserver(version) {
    if (window.__reflex?.version === version)
        return window.__reflex;
    const ids = new WeakMap();
    const nodes = new Map();
    let next = 1;
    const identity = (e) => {
        let id = ids.get(e);
        if (id === undefined) {
            id = next++;
            ids.set(e, id);
        }
        nodes.set(id, e);
        return id;
    };
    const ROLES = new Set(["button", "link", "checkbox", "radio", "switch", "tab", "menuitem", "menuitemradio",
        "menuitemcheckbox", "option", "gridcell", "row", "combobox", "textbox", "searchbox", "spinbutton"]);
    const SELECTOR = "a[href],button,input,textarea,select,summary,[contenteditable=\"true\"]," +
        [...ROLES].map((r) => `[role="${r}"]`).join(",");
    const SECRET_TYPES = new Set(["password", "hidden", "file"]);
    const OWNING_ROLES = new Set(["link", "button", "option", "menuitem", "tab"]);
    const visible = (e) => !e.closest("[aria-hidden=\"true\"],[inert]") && e.checkVisibility({ checkOpacity: true, checkVisibilityCSS: true });
    const disabled = (e) => e.matches(":disabled") || e.closest("[aria-disabled=\"true\"]") !== null;
    const accessibleName = (e, seen = new Set()) => {
        if (!e || seen.has(e))
            return "";
        seen.add(e);
        const labelledBy = (e.getAttribute("aria-labelledby") ?? "").split(/\s+/).filter(Boolean)
            .map((id) => accessibleName(document.getElementById(id), seen)).filter(Boolean).join(" ");
        const input = e;
        const fromLabels = [...(input.labels ?? [])].map((l) => accessibleName(l, seen)).filter(Boolean).join(" ");
        const buttonValue = ["button", "submit", "reset"].includes(input.type) ? input.value : "";
        const text = e.tagName === "INPUT" || e.tagName === "SELECT" || e.tagName === "TEXTAREA" ? "" :
            [...e.childNodes].map((n) => n.nodeType === Node.TEXT_NODE ? n.textContent ?? ""
                : n.nodeType === Node.ELEMENT_NODE && n.getAttribute("aria-hidden") !== "true"
                    ? accessibleName(n, seen) : "").join(" ");
        const name = labelledBy || e.getAttribute("aria-label") || fromLabels || buttonValue ||
            e.getAttribute("alt") || text || e.getAttribute("title") || e.getAttribute("placeholder") || "";
        return name.replace(/\s+/g, " ").trim();
    };
    const roleOf = (e) => {
        const explicit = e.getAttribute("role");
        if (explicit && ROLES.has(explicit)) {
            return (explicit.startsWith("menuitem") ? "menuitem" : explicit);
        }
        const input = e;
        switch (e.tagName) {
            case "BUTTON":
            case "SUMMARY": return "button";
            case "A": return "link";
            case "SELECT": return "select";
            case "TEXTAREA": return "textbox";
            case "INPUT":
                if (input.type === "checkbox" || input.type === "radio")
                    return input.type;
                if (["button", "submit", "reset", "image"].includes(input.type))
                    return "button";
                if (input.type === "search")
                    return "searchbox";
                if (input.type === "number")
                    return "spinbutton";
                if (["text", "email", "url", "tel", ""].includes(input.type))
                    return "textbox";
                return null;
        }
        return e.isContentEditable ? "textbox" : null;
    };
    const isEditable = (e, role) => {
        const input = e;
        if (input.readOnly || e.getAttribute("aria-readonly") === "true")
            return false;
        if (role === "textbox" || role === "searchbox" || role === "spinbutton")
            return true;
        return role === "combobox" && (e.tagName === "INPUT" || e.tagName === "TEXTAREA");
    };
    const valueOf = (e, role) => {
        if (e.tagName === "SELECT")
            return [...e.selectedOptions].map((o) => o.label).join(", ");
        if ("value" in e && typeof e.value === "string" && role !== "button") {
            return e.value;
        }
        if (e.isContentEditable || role === "combobox")
            return e.innerText.trim();
        return undefined;
    };
    /** The box a control lives in, used for duplicate-name context and guards. */
    const scopeOf = (e) => e.closest("li,tr,[role=\"row\"],article,section,form,dialog,[role=\"dialog\"]") ?? e.parentElement;
    const inViewport = (r) => r.width > 0 && r.height > 0 && r.bottom > 0 && r.right > 0 && r.top < innerHeight && r.left < innerWidth;
    /** A control is covered when the topmost element at its centre is neither it nor inside it. */
    const centre = (e) => {
        const r = e.getBoundingClientRect();
        const x = Math.min(Math.max(r.left + r.width / 2, 0), innerWidth - 1);
        const y = Math.min(Math.max(r.top + r.height / 2, 0), innerHeight - 1);
        const top = document.elementFromPoint(x, y);
        if (!top || !(e === top || e.contains(top) || top.contains(e) && top.tagName === "LABEL"))
            return null;
        return { x, y };
    };
    const formValues = () => [...document.querySelectorAll("input,textarea,select")]
        .filter((e) => !SECRET_TYPES.has(e.type))
        .map((e) => {
        const f = e;
        return [identity(e), f.value, f.checked, e.selectedIndex, f.disabled];
    });
    const pageKey = () => JSON.stringify([performance.timeOrigin, location.href, scrollX, scrollY, innerWidth, innerHeight, formValues()]);
    const guard = (id) => {
        const found = nodes.get(id);
        if (!found?.isConnected || !visible(found))
            return null;
        // A label stands in for its hidden checkbox or radio; guard the control's state, not the label's.
        const e = found.tagName === "LABEL" ? found.control ?? found : found;
        const role = roleOf(e);
        return JSON.stringify([id, role, accessibleName(e), role ? valueOf(e, role) : null, disabled(e),
            e.getAttribute("aria-expanded"), e.getAttribute("aria-checked"), e.getAttribute("aria-selected"),
            e.getAttribute("href"), scopeOf(e)?.innerText?.slice(0, 2000) ?? ""]);
    };
    const visibleText = (max) => {
        const words = [];
        const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
        const range = document.createRange();
        let length = 0;
        for (let n = walker.nextNode(); n && length < max; n = walker.nextNode()) {
            const value = n.textContent?.trim();
            const parent = n.parentElement;
            if (!value || !parent || parent.closest("script,style,noscript,template") || !visible(parent))
                continue;
            range.selectNodeContents(n);
            if (!inViewport(range.getBoundingClientRect()))
                continue;
            words.push(value);
            length += value.length + 1;
        }
        return words.join("\n").slice(0, max);
    };
    const observer = {
        version,
        pageKey,
        guard,
        observe({ maxElements, maxTextChars }) {
            if (!document.body)
                return null;
            for (const [id, e] of nodes)
                if (!e.isConnected)
                    nodes.delete(id);
            const found = [];
            for (const e of document.querySelectorAll(SELECTOR)) {
                const role = roleOf(e);
                if (!role || SECRET_TYPES.has(e.type) || disabled(e))
                    continue;
                // Custom checkboxes and radios hide the input and style its label; the label is what a person clicks.
                let target = e;
                if ((role === "checkbox" || role === "radio") && (!visible(e) || !centre(e))) {
                    const label = [...(e.labels ?? [])].find((l) => visible(l) && inViewport(l.getBoundingClientRect()) && centre(l));
                    if (!label)
                        continue;
                    target = label;
                }
                if (!visible(target) || !inViewport(target.getBoundingClientRect()) || !centre(target))
                    continue;
                // A grid cell that only wraps a button is represented by the button.
                if (role === "gridcell" && e.querySelector("button,[role=\"button\"]"))
                    continue;
                const owner = e.parentElement?.closest(SELECTOR);
                const ownerRole = owner ? roleOf(owner) : null;
                if (ownerRole && OWNING_ROLES.has(ownerRole) && !isEditable(e, role))
                    continue;
                let name = accessibleName(e);
                if (!name && (role === "row" || role === "gridcell" || role === "option")) {
                    name = (e.innerText ?? "").replace(/\s+/g, " ").trim().slice(0, 80);
                }
                const editable = isEditable(e, role);
                const box = target.getBoundingClientRect();
                const entry = {
                    node: identity(target), role, name: name || role, editable,
                    rect: { x: Math.round(box.x), y: Math.round(box.y), w: Math.round(box.width), h: Math.round(box.height) },
                };
                const value = valueOf(e, role);
                if (value)
                    entry.value = value.slice(0, 200);
                for (const key of ["checked", "selected", "expanded"]) {
                    const v = e.getAttribute(`aria-${key}`);
                    if (v !== null)
                        entry[key] = v;
                }
                if (role === "checkbox" || role === "radio")
                    entry.checked = String(e.checked);
                if (e.tagName === "SELECT") {
                    entry.options = [...e.options]
                        .filter((o) => !o.selected && !o.disabled && !o.closest("optgroup[disabled]"))
                        .slice(0, 50).map((o) => ({ value: o.value, label: o.label }));
                }
                found.push({ e, entry });
            }
            const counts = new Map();
            for (const { entry } of found)
                counts.set(entry.name, (counts.get(entry.name) ?? 0) + 1);
            const elements = found.slice(0, maxElements).map(({ e, entry }, i) => {
                const element = { id: `e${i + 1}`, ...entry };
                if ((counts.get(entry.name) ?? 0) > 1) {
                    const scope = scopeOf(e)?.innerText?.replace(/\s+/g, " ").trim();
                    if (scope && scope !== entry.name)
                        element.context = scope.slice(0, 80);
                }
                return element;
            });
            const guards = {};
            for (const el of elements)
                guards[el.node] = guard(el.node) ?? "";
            const active = document.activeElement ? ids.get(document.activeElement) : undefined;
            const focused = elements.find((el) => el.node === active)?.id;
            return {
                url: location.href,
                title: document.title,
                viewport: { width: innerWidth, height: innerHeight },
                scroll: { y: Math.round(scrollY), height: document.documentElement.scrollHeight },
                text: visibleText(maxTextChars),
                elements,
                omitted: Math.max(0, found.length - maxElements),
                ...(focused ? { focused } : {}),
                pageKey: pageKey(),
                guards,
            };
        },
        locate(id, editable) {
            const e = nodes.get(id);
            if (!e?.isConnected || disabled(e) || !visible(e))
                return null;
            if (editable && (e.readOnly || e.getAttribute("aria-readonly") === "true"))
                return null;
            if (!inViewport(e.getBoundingClientRect()))
                e.scrollIntoView({ block: "center", inline: "center" });
            return centre(e);
        },
        choose(id, value) {
            const e = nodes.get(id);
            if (!(e instanceof HTMLSelectElement) || disabled(e))
                return false;
            const option = [...e.options].find((o) => o.value === value && !o.disabled && !o.closest("optgroup[disabled]"));
            if (!option)
                return false;
            e.value = value;
            e.dispatchEvent(new Event("input", { bubbles: true }));
            e.dispatchEvent(new Event("change", { bubbles: true }));
            return true;
        },
        settle(id, capMs) {
            return new Promise((resolve) => {
                const field = id === null ? undefined : nodes.get(id);
                const suggests = field !== undefined && (field.getAttribute("role") === "combobox" || field.hasAttribute("aria-autocomplete"));
                let frames = 0;
                let done = false;
                const finish = () => { done = true; resolve(); };
                setTimeout(finish, suggests ? capMs : Math.min(capMs, 50));
                const tick = () => {
                    if (done)
                        return;
                    const owned = (field?.getAttribute("aria-controls") ?? field?.getAttribute("aria-owns") ?? "").split(/\s+/).filter(Boolean);
                    const roots = owned.length ? owned.map((o) => document.getElementById(o)).filter((r) => r !== null) : [document];
                    const shown = roots.some((r) => [...r.querySelectorAll("[role=\"option\"]")].some((o) => inViewport(o.getBoundingClientRect())));
                    if (++frames >= 2 && (!suggests || shown))
                        finish();
                    else
                        requestAnimationFrame(tick);
                };
                requestAnimationFrame(tick);
            });
        },
    };
    window.__reflex = observer;
    return observer;
}
