#!/usr/bin/env python3
"""Copy the shared observers from a solari-reflex checkout into this fork.

    python scripts/sync_reflex.py /path/to/solari-reflex

solari-reflex (https://github.com/hitakshiA/solari-reflex) is the reference
speed layer. Browsers and desktops are read by two pieces of it, and this fork
ships both as package data so the Python SDK reads screens exactly as the TS
agent and the MCP fork do:

- ``dist/page/observer.js`` -> ``solari_browser/observer.js``: the in-page
  observer. Only ``installObserver`` is kept (it is self-contained by design);
  the ``OBSERVER_VERSION`` it was built with goes in the header. Run
  ``npm run build`` in solari-reflex first if ``dist/`` is missing.
- ``src/desktop/reflexd.py`` -> ``solari_core/reflexd/reflexd.py``: the
  accessibility-tree daemon installed into desktops, copied byte for byte.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OBSERVER_OUT = ROOT / "packages/solari_browser/solari_browser/observer.js"
REFLEXD_OUT = ROOT / "packages/solari_core/solari_core/reflexd/reflexd.py"


def main(argv: list) -> int:
    if len(argv) != 2:
        print(__doc__.strip().splitlines()[2].strip(), file=sys.stderr)
        return 2
    reflex = Path(argv[1]).resolve()

    built = (reflex / "dist/page/observer.js").read_text(encoding="utf-8")
    version = re.search(r"export const OBSERVER_VERSION = (\d+);", built)
    install = re.search(r"^export (function installObserver\(version\) \{.*?^\})$", built, re.S | re.M)
    if not version or not install:
        raise SystemExit("could not find installObserver and OBSERVER_VERSION in dist/page/observer.js")
    OBSERVER_OUT.write_text(
        "// Generated by scripts/sync_reflex.py from solari-reflex dist/page/observer.js. Do not edit.\n"
        f"// OBSERVER_VERSION = {version.group(1)}\n"
        f"{install.group(1)}\n",
        encoding="utf-8",
    )

    REFLEXD_OUT.parent.mkdir(parents=True, exist_ok=True)
    REFLEXD_OUT.write_bytes((reflex / "src/desktop/reflexd.py").read_bytes())

    print(f"wrote {OBSERVER_OUT.relative_to(ROOT)} (observer v{version.group(1)})")
    print(f"wrote {REFLEXD_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
